@baseUrl = http://localhost:5124

@userId=sandro.chierici

### Create Upload Token
# @name login
POST {{baseUrl}}/api/v1/ingestion/json/preflight/{{userId}}
Content-Type: application/json

{
  "userId": {{userId}}
}


### Upload JSON File
POST {{baseUrl}}/api/v1/ingestion/json/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryilhrIWvBeO8R2OKV
five0-jsonupload: {{login.response.body.$.token}}

------WebKitFormBoundaryilhrIWvBeO8R2OKV
Content-Disposition: form-data; name="file"; filename="test.json"
Content-Type: application/json

{
  "specificProperty": "exampleValue"
}
------WebKitFormBoundaryilhrIWvBeO8R2OKV--
