@ResourceManager_HostAddress = http://localhost:6085

###
GET {{ResourceManager_HostAddress}}/api/v1/tenant/019adae9-ad3b-7ae5-8719-3c30b308aacb/resources/RES002
Accept: application/json

###
POST {{ResourceManager_HostAddress}}/api/v1/tenant/019adae9-ad3b-7ae5-8719-3c30b308aacb/resources/_search
Accept: application/json
Content-Type: application/json

{
    "resourceCode": ["RES001","RES002","RES003","RES004","RES005","RES006","RES007","RES008","RES009","RES010"]
}

###
POST {{ResourceManager_HostAddress}}/api/v1/tenant/019adae9-ad3b-7ae5-8719-3c30b308aacb/resources
Accept: application/json
Content-Type: application/json

{
    "resourceCode": "RES002",
    "name": "Resource 1",
    "description": "Resource 2",
    "resourceGroupCode": "MAIN_GROUP"
}

###
GET {{ResourceManager_HostAddress}}/api/v1/commands/createdb
Accept: application/json

###
GET {{ResourceManager_HostAddress}}/api/health/ready
Accept: application/json

###
GET {{ResourceManager_HostAddress}}/api/health/live
Accept: application/json

###
GET {{ResourceManager_HostAddress}}/api/health/startup
Accept: application/json

### test timeservice
###
GET http://locahost:6081/api/v1/now
Accept: application/json